apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: <database-host>
            - name: WORDPRESS_DB_USER
              value: <database-username>
            - name: WORDPRESS_DB_PASSWORD
              value: <database-password>
            - name: WORDPRESS_DB_NAME
              value: <database-name>
